import type { Metadata } from "next";
import Sidebar from "@/components/layouts/sidebar";


export const metadata: Metadata = {
  title: "NextJS CRM",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <div
      className='antialiased pl-[15rem]'
    >
      <Sidebar />
      {children}
    </div>
  );
}
